### ISSUE TITLE
Create an example program that gives feedback to the driver via rumble

### ISSUE THREAD

**Issue by ArchdukeTim** [AquidneckIslandRobotics/FRC78_2024#21]
The joysticks that we currently use have the ability to rumble. We can use this as quick feedback to the driver rather than relying on something on the dashboard or visuals. We should create an example program that spins a motor up, and then when it's at velocity the joystick rumbles. The rumble should be short, but long enough to not miss

**Comment by tsieben** [comment]
Rumble has been integrated into the drive control, needs further refinement but is covered in another issue.
