### ISSUE TITLE
Move drive command to Chassis class

### ISSUE THREAD

**Issue by ArchdukeTim** [AquidneckIslandRobotics/FRC78_2024#34]
The drive command is quite hefty right now. The drive command should be converted to a factory method that accepts a `ChassisSpeeds` object only. No joystick config should happen in the drive command, so it can be used by auto modes / subroutines if necessary. 

The joystick dead banding / trigger modification should probably happen in `RobotContainer`, and all values adjusted before creating a `ChassisSpeeds`

**Comment by siebs7317** [comment]
The Drive commmand has been moved to the subsystem.
