### ISSUE TITLE
Add a soft-limit for the elevator

### ISSUE THREAD

**Issue by ArchdukeTim** [AquidneckIslandRobotics/FRC78_2024#52]
The elevator only has a limit switch on the bottom but we need to prevent it from running too far up. Tess and I calculated the position conversion factor already by multiplying the diameter of the chain sprocket (1.751 inches) by pi to get the circumference (5.501). This means each rotation of the encoder is equal to 5.501 inches of chain travel. 

Add in a soft limit to the motor that the encoder is connected to (motor 11) that will keep the elevator 1inche below the top. We can adjust this value as we become more confident in the code's abilities.

**Comment by tsieben** [comment]
There is a homing routine that happens at the start and setups the soft limits
