### ISSUE TITLE
Create a zeroing routine for the elevator

### ISSUE THREAD

**Issue by ArchdukeTim** [AquidneckIslandRobotics/FRC78_2024#53]
The elevator needs to be zeroed each time the robot starts up. We can bind this to a button for now, but eventually it will happen each time the robot turns on.

https://github.com/AquidneckIslandRobotics/FRC78_2024/blob/tim/tutorials/tutorials/elevator_zeroing.md

**Comment by tsieben** [comment]
Has been created and is working.
