### ISSUE TITLE
Create wrist subsystem

### ISSUE THREAD

**Issue by ArchdukeTim** [AquidneckIslandRobotics/FRC78_2024#54]
Contains a spark max motor controller with an absolute encoder. Add simple commands that  move the wrist angle 'up' and 'down' (up points the wrist more toward the sky) and has soft-limits based on the encoder reading. 

Plug the wrist encoder into a spark on the test board to get preliminary readings for encoder limits

**Comment by lizrobots** [comment]
Implemented
