### ISSUE TITLE
Elevator subsystem inside chassis package

### ISSUE THREAD

**Issue by tsieben** [AquidneckIslandRobotics/FRC78_2024#59]
The Elevator subsystem should be moved out of the chassis package.

https://github.com/AquidneckIslandRobotics/FRC78_2024/blob/2d95d903b6269eba2ebda902ed1b7d2748a64970/src/main/java/frc/robot/subsystems/chassis/Elevator.java#L5

**Comment by siebs7317** [comment]
this issue has been resolved
